### ISSUE TITLE
Create an autocomplete editor for GIFT

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/GIFT-grammar-PEG.js#2]
GIFT isn't so user-friendly, but perhaps it could be helped by autocompletion inside a smart editor? With a grammar this should be feasible. Precedent with PEG.js exists given this answer on stackoverflow: http://stackoverflow.com/a/7857785/1168342

Here's a grammar with a kind of auto-complete: https://github.com/mstefaniuk/Concrete-Freetext/blob/master/grammar/concrete-grammar-template.pegjs

**Comment by ethan-ou** [comment]
Another approach to doing this is to lean on the Monaco editor for providing autocompletions. The editor provides an API for doing this through ```monaco.languages.registerCompletionItemProvider```, which lets you define keywords that autocomplete into snippets of code.  You can see an example of this in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example).

I believe the Monaco editor also has many more functions that allow for smart code checking, highlighting of improper syntax etc.

**Comment by fuhrmanator** [comment]
Closing this as the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=ethan-ou.vscode-gift-pack) does an excellent job!
