### ISSUE TITLE
How can I parse cyrillic symbols correctly (for ukrainian and russian languages)?

### ISSUE THREAD

**Issue by yaroslavslon** [fuhrmanator/GIFT-grammar-PEG.js#28]
For example I have gift file
`::Вопрос-описание::Данный тест содержит следующие темы...`
console.log give this result
![2018-09-28 18 15 49](https://user-images.githubusercontent.com/15836227/46218235-c8e23980-c34c-11e8-8cdc-6304f1189470.png)
How to fix this?

**Comment by fuhrmanator** [comment]
Hello, using the online validator, it seems OK. Have a look:

https://fuhrmanator.github.io/GIFT-grammar-PEG.js/docs/editor/editor.html?text=9OlD3G8X60LReG4fWEhuy6H8F1WByG06ex0jpEje0M_pVYO47WmEHORiif0cuqMdKUVytDoL-JWbgap9oHYK6I9lsh_uKYcwwgxRKlUPdxBt_WG0

![image](https://user-images.githubusercontent.com/7606540/46227457-439b5c80-c32d-11e8-8ab9-e3ffb242c8e3.png)


Could it be just that console.log doesn't do well displaying multi-byte characters?

**Comment by yaroslavslon** [comment]
It's my fault. I misread gift file. All works fine.
