### ISSUE TITLE
Matching Questions

### ISSUE THREAD

**Issue by stefanhuber** [fuhrmanator/GIFT-grammar-PEG.js#34]
There is some strange behaiviour in matching questions, e.g.:

```
Please match the following\:
{
  =abc -> ...
  =xyz -> , . ,
}
```

Symbols like `.` and `,` lead to errors in the parser, however don't show where the error is (e.g. give line number), as done with other errors. I am not sure if this is "correct". I tried the Moodle Import for the above question and it works correctly.

**Comment by stefanhuber** [comment]
`PlainText` might be set to something different:
https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/master/GIFT.pegjs#L93

**Comment by fuhrmanator** [comment]
Sorry for the late reply! Thanks for reporting this. 

Are you sure you have the latest version of the grammar? I just tried it with the latest grammar and it appears to parse correctly:

![image](https://user-images.githubusercontent.com/7606540/85439108-a77ea380-b55a-11ea-865f-fab9678fb103.png)

The result is:

```json
[
   {
      "type": "Matching",
      "title": null,
      "stem": {
         "format": "moodle",
         "text": "Please match the following:"
      },
      "hasEmbeddedAnswers": false,
      "globalFeedback": null,
      "matchPairs": [
         {
            "subquestion": {
               "format": "moodle",
               "text": "abc"
            },
            "subanswer": "..."
         },
         {
            "subquestion": {
               "format": "moodle",
               "text": "xyz"
            },
            "subanswer": ", . ,"
         }
      ]
   }
]
```

I'm happy to re-open if you can find a test-case that doesn't parse. The best way is to fork the project put a new test file in `tests/questions/myExampleThatDoesNotWork.gift` with what should be its corresponding `.json` (you can use the online editor as shown in the screenshot above -- you have to copy/paste the current grammar on the left).

**Comment by stefanhuber** [comment]
Thank you for your answer. Maybe this just concerns the online editor:

![grafik](https://user-images.githubusercontent.com/5379359/85508480-72269400-b5f4-11ea-856b-1daa94cea5af.png)

**Comment by fuhrmanator** [comment]
@stefanhuber indeed you have found a bug in that prototype editor. I see the problem now. My crude way to draw lines between the left and right entries with SVG.

**Comment by fuhrmanator** [comment]
Fixed - see this [example](https://fuhrmanator.github.io/GIFT-grammar-PEG.js/editor/editor.html?text=fP11Ynin38NFzQyGzD92F7CFfD3IIm-5GEWj5uz7CsEmhQaaPzeD-z_NJjXTTg-hWq7IztZMEqPqWf2S-WLqGPWeHjf2dizxSpK01pTuiD-WwxhM_Vl_qBeTTB0pZyPyL6z-loWnOiAi0ZI1WrIYXZKY-8M2HmYA2RQWDpPmzU7a8cINKC1vJpnMKr22HNMLyxxl_QJTnUKHUGXHEnnBFvSmebWfWrtTZD9l7BJgx4mqscTFU_UqYgBsRwble2pzUGzNy-a0HwOXOcftd1HJ6vtAF5SCHn2AvOQtzVUeoDbfkA0qx4TbmBqERqoM3RbjVsLFpEWLlX13o1Do8FxwNl0pYBBpIcoWrkTQy4Vg4MypMJ2kSa_CKqeb1-_QnxeM-nC0) - thanks for reporting!
