### ISSUE TITLE
Support parsing tags (in comments)

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/GIFT-grammar-PEG.js#44]
GIFT format supports tags in comments, see https://tracker.moodle.org/browse/MDL-68338

**Comment by jmoseman01** [comment]
Are there any plans to get this to work?  I was planning on using this GIFT parser for my software.  I can help, but I might just use moodle xml at this point.

**Comment by fuhrmanator** [comment]
@jmoseman01 I created a branch to support this - https://github.com/fuhrmanator/GIFT-grammar-PEG.js/tree/support-id-and-tags-in-comments -- I'd be happy if you can check it out to see if it does what you need and if so I can merge into the master.
Edit: It's in #47

**Comment by fuhrmanator** [comment]
Heads up @ethan-ou if you want to support the `id` and `tags` in the preview for the question objects returned by this upcoming version of the parser. See the new tests in #47 if you're curious.

**Comment by ethan-ou** [comment]
Not a problem. What's your progress now on it? And would you like me to submit another pull request to update the Typescript typings?

**Comment by fuhrmanator** [comment]
Sure - I appreciate the TypeScript typing updates. It would be better if we could work together on these in a single PR I guess.
