### ISSUE TITLE
Bug-True or false with 2 feedback

### ISSUE THREAD

**Issue by Girardvjonathan** [fuhrmanator/GIFT-grammar-PEG.js#5]
## Context
True or false with feedback for positive and negative answer dont get parse correctly:
## Exemple:
Grant is buried in Grant's tomb.{FALSE#wrong answer feedback#right answer feedback}
### Result JSON:
```
[
   {
      "type": "TF",
      "title": null,
      "stem": "Grant is buried in Grant's tomb.",
      "hasEmbeddedAnswers": false,
      "isTrue": false,
      "feedBack1": "right answer feedback",
      "feedBack2": undefined
   }
]
```
### Expected JSON:
```
[
   {
      "type": "TF",
      "title": null,
      "stem": "Grant is buried in Grant's tomb.",
      "hasEmbeddedAnswers": false,
      "isTrue": false,
      "feedBack1": "right answer feedback",
      "feedBack2": "wrong answer feedback"
   }
]
```

**Comment by fuhrmanator** [comment]
I confirm the bug. Working on a solution that doesn't break the other feedback. I'm going to add your sample question and expected JSON to the tests/question directory.

In the expected JSON, it's perhaps more consistent with the GIFT standard to have the wrong answer feedback be first (i.e., like in the question you gave).  

It's also imaginable to change the JSON names to `correctFeedback` and `incorrectFeedback` to avoid the confusion.
