### ISSUE TITLE
This question is shown as error but its correct (unescaped : and = in question stem)

### ISSUE THREAD

**Issue by ejgutierrez74** [fuhrmanator/GIFT-grammar-PEG.js#53]
// true/false
::Q1:: Es 1+1:=2 {
T}

**Comment by fuhrmanator** [comment]
Why do you say it's correct?

When I create your question in Moodle and export it as GIFT, here is what I get:

```
::Q1::Es 1+1\:\=2{TRUE}
```

The GIFT standard says that `:` should be escaped:

> \character | Backslash escapes the special meaning of ~, =, #, {, }, and :

 https://docs.moodle.org/401/en/GIFT_format#Format_symbols

**Comment by ejgutierrez74** [comment]
Sorry i was confused by;
https://docs.moodle.org/all/es/Formato_GIFT#Opci.C3.B3n_m.C3.BAltiple_con_varias_respuestas_correctas

Where you can see:
```
Aquí hay algunos ejemplos rápídos:

// falso/verdadero
::Q1:: 1+1=2 {T}
```
but in some tutorials i read that you are right should be ::Q1:: 1+1\=2 {T}

**Comment by fuhrmanator** [comment]
Your point is interesting. I think the PHP parser (on Moodle) might accept the `=` and the `:` without escaping because they are not inside the answer definition `{`...`}`. Supporting that with the grammar is added complexity, especially given how Moodle's export works and the docs are written.

**Comment by fuhrmanator** [comment]
I'll close this issue for now. If it's a big problem for people, maybe someone can propose a fix to the grammar.
