### ISSUE TITLE
Parsing fails with negative value in numerical questions

### ISSUE THREAD

**Issue by dullin** [fuhrmanator/GIFT-grammar-PEG.js#55]
When using a numerical question, having a negative value is considered an error where it shouldn't be.

Here is an example:

```js
import { parse } from "gift-pegjs";

const question = "What is the value of -1? {#-1}."

const quiz = parse(question)

```

**Comment by fuhrmanator** [comment]
Indeed! The grammar doesn't take into consideration signed numbers (how silly!). 

I don't have a lot of bandwidth right now to work on this - it's an easy fix, but requires adding tests (such as your example that doesn't work). 

The key fix is changing the lines at https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/0cb57354f4d493f2a6609047efc1af68c5c2a1f9/GIFT.pegjs#L294-L301

with 

```peg
Number
  = value:DecimalValue { return parseFloat(value.join('')); }

DecimalValue
  = IntegerPart ('.' FractionalPart)?

IntegerPart
  = Sign? Digits

FractionalPart
  = Digits

Sign
  = [+-]

Digits
  = [0-9]+
```

**Comment by Sho-ki** [comment]
I created a [PR](https://github.com/fuhrmanator/GIFT-grammar-PEG.js/pull/56) for this issue.

**Comment by fuhrmanator** [comment]
Thanks @Sho-ki for your PR
