### ISSUE TITLE
Consider not removing additional spaces and new lines in also in Markdown like HTML

### ISSUE THREAD

**Issue by livinNector** [fuhrmanator/GIFT-grammar-PEG.js#60]
The `RichText` and `MatchRichText` are removing the extra lines and spaces from the markdown since only `format !== "html"` is specified. This is causing some features of markdown like paragraphs and tables to break with an escaped string unlike html. since any markdown parser will removes those extra lines by itself it should not be removed by the gift parser.

**Comment by fuhrmanator** [comment]
Thanks for this report! 

Can you provide me with some examples so we can write a test? See https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/master/tests/questions/shortFirstEmbeddedUnderlineHTML.gift and https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/master/tests/questions/shortFirstEmbeddedUnderlineHTML.json for an example.

Better still, you can write a test and make a PR -- my semester is pretty full and I'm not sure I can look at this until the fall.

**Comment by fuhrmanator** [comment]
Thanks @livinNector for the PR. Before I can merge, I want to verify what happens with the online editor at https://github.com/fuhrmanator/GIFT-grammar-PEG.js/tree/master/docs/editor, which is (unfortunately?) part of this repo.

**Comment by fuhrmanator** [comment]
Fixed by #61

**Comment by fuhrmanator** [comment]
For transparency, here's the view in the online editor:

Before this fix:

![image](https://github.com/fuhrmanator/GIFT-grammar-PEG.js/assets/7606540/98b4ec6e-6010-4fa1-ba53-1a05d6e32d9d)

After:

![image](https://github.com/fuhrmanator/GIFT-grammar-PEG.js/assets/7606540/ef407e15-fb0a-4134-a869-bfd2ab08760a)
