### ISSUE TITLE
Ambiguity and misalignment of feedback on True - False questions

### ISSUE THREAD

**Issue by livinNector** [fuhrmanator/GIFT-grammar-PEG.js#62]
@fuhrmanator, sorry to bother you again. I have been working around to build a formatter as #43, while I was trying to build it. I came to notice that there seems to be a swap in the feedback for the true and false, and this has been assumed in the parser also. 

It is coming from the terms `correctFeedback` and `incorrectFeedback`, where the first feedback is taken for `incorrectFeedback` and second feedback is taken for `correctFeedback`. 

I have been checking this with the moodle and the @ethan-ou's VS Code extension. The assuming that the first feedback is for the `True` and the second feedback is for `False`.

I suggest that it should be renamed as `trueFeedback` and `falseFeedback`. 

The current implementation parsers the below 
```gift
Grant is buried in Grant's tomb.{FALSE#No one is buried in Grant's tomb.}
```
into 

```json
{
        "id" : null,
        "tags" : null,
        "type": "TF",
        "title": null,
        "stem": {"format":"moodle", "text":"Grant is buried in Grant's tomb."},
        "hasEmbeddedAnswers": false,
        "globalFeedback": null,
        "isTrue": false,
        "incorrectFeedback": {"format":"moodle", "text":"No one is buried in Grant's tomb."},
        "correctFeedback": null
}
```

this `incorrectFeedback` is rendered as the feedback for the True response in the VS code extension and in the moodle also.

Some tests like [options1.txt](https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/master/tests/questions/options1.gift)

Also I see that #5 here it is renamed from `feedback1` and  `feedback2` to the `incorrectFeedback` and `correctFeedback`.

shouldn't we consider renaming `incorrectFeedback` to `TrueFeedback` and `correctFeedback` to `FalseFeedback`? so that the naming is not confusing since they are the feedback for True and False  respectively.

**Comment by fuhrmanator** [comment]
I appreciate the issues. It's important to point them out. 

Your suggestion for renaming seems reasonable. If you're interested in doing a PR, it's welcome. 

I won'tbe able to spend time on this issue until after August.
