### ISSUE TITLE
Spaces and lines are removed from html/markdown when format is inferred

### ISSUE THREAD

**Issue by livinNector** [fuhrmanator/GIFT-grammar-PEG.js#64]
This is related to the #60, In the `MatchRichText` and `RichText` block, when the format is inferred, the way the text is processed is not consistent.

**Example GIFT**  
```
[markdown] This is a  
multiline markdown { 
= first line  
second line
= [markdown] another first line  
another second line
}
```

**JSON**
```
[
  {
    "type": "Short",
    "title": null,
    "stem": {
      "format": "markdown",
      "text": "line1  \nline2"  # HERE
    },
    "hasEmbeddedAnswers": false,
    "globalFeedback": null,
    "choices": [
      {
        "isCorrect": true,
        "weight": null,
        "text": {
          "format": "markdown",
          "text": "line1 line2" # HERE
        },
        "feedback": null
      },
      {
        "isCorrect": true,
        "weight": null,
        "text": {
          "format": "markdown",
          "text": "another line1  \nanother line2" HERE
        },
        "feedback": null
      }
    ],
    "id": null,
    "tags": null
  }
]
```

In the first option, even though the type is inferred as Markdown, it is parsed as plain text, removing the line and space by the fix in. This is also true for HTML.

I suspect that the format inferred is not being used in the type check while processing [here](https://github.com/livinNector/GIFT-grammar-PEG.js/blob/bef4cc68785bb77c20de7376fe34958949279da8/GIFT.pegjs#L288-L305).

**Comment by fuhrmanator** [comment]
I think I understand what you're saying, but your example code is confusing because the JSON seems to have different content than the sample GIFT. 

Please give a set of test files of how it should work. Then we can make it work as expected.

It could be a bug with set/getLastQuestionTextFormat() logic, but until we have a reproducible bug it is not useful to make guesses.

**Comment by livinNector** [comment]
Made a [gist](https://gist.github.com/livinNector/e697f565b355c04503df56a2963910fd) with the sample gift file, actual and expected JSON files. Kindly check these out and let me know if it is ok.

**Comment by livinNector** [comment]
I have found what is causing the issue.
It is not the bug with the getLastQuestionTextFormat() because the format is predicted correctly as markdown.
```js
MatchRichText "(formatted text excluding '->')"
  = format:Format? _ txt:MatchTextChar+ { return {
      format:(format!==null ? format : getLastQuestionTextFormat()), 
      text:(
          (format !== "html" && format !== "markdown") ? 
            escapedCharacterDecode(removeNewLinesDuplicateSpaces(txt.join('').trim())) :
            escapedCharacterDecode(txt.join('')).replace(/\r\n/g,'\n').trim()
          )}}  // avoid failing tests because of Windows line breaks 
```

It is the confusion between the variable `format` and the property `format` in the return object. It should be like we should infer the format outside the return and use the `inferredFormat` in both the properties of the return object. Because in the current implementation we are only using the actual format rather than the inferred format in the checks in the `text` property.
